import { ChatContact, ChatMessage } from '@/components/chat/types'

// Mock current user ID
export const CURRENT_USER_ID = 'current-user-1'

// Mock chat contacts
export const mockChatContacts: ChatContact[] = [
  {
    id: 'chat-1',
    name: 'Jacquenetta Slowgrave',
    initials: 'JS',
    isOnline: true,
    lastMessage: 'Great! Looking forward to it. See you later!',
    lastMessageTime: '10 minutes',
    unreadCount: 8,
  },
  {
    id: 'chat-2',
    name: 'Nickola Peever',
    initials: 'NP',
    isOnline: true,
    lastMessage: 'Sounds perfect! I\'ve been wanting to try that place. See you there!',
    lastMessageTime: '40 minutes',
    unreadCount: 2,
  },
  {
    id: 'chat-3',
    name: 'Farand Hume',
    initials: 'FH',
    isOnline: true,
    lastMessage: 'How about 7 PM at the new Italian place downtown?',
    lastMessageTime: 'Yesterday',
  },
  {
    id: 'chat-4',
    name: 'Ossie Peasey',
    initials: 'OP',
    isOnline: false,
    lastMessage: 'Hey Bonnie, yes, definitely! What time should we meet?',
    lastMessageTime: '13 days',
  },
  {
    id: 'chat-5',
    name: 'Hall Negri',
    initials: 'HN',
    isOnline: false,
    lastMessage: 'No worries at all! I\'ll grab a table and wait for you. Drive safe!',
    lastMessageTime: '2 days',
  },
  {
    id: 'chat-6',
    name: 'Elyssa Segot',
    initials: 'ES',
    isOnline: false,
    lastMessage: 'She just told me today.',
    lastMessageTime: 'Yesterday',
  },
  {
    id: 'chat-7',
    name: 'Gil Wilfing',
    initials: 'GW',
    isOnline: false,
    lastMessage: 'See you in 5 minutes!',
    lastMessageTime: '1 day',
  },
  {
    id: 'chat-8',
    name: 'Bab Cleaton',
    initials: 'BC',
    isOnline: false,
    lastMessage: 'If it takes long you can mail',
    lastMessageTime: '3 hours',
  },
  {
    id: 'chat-9',
    name: 'Janith Satch',
    initials: 'JS',
    isOnline: true,
    lastMessage: 'Absolutely! It\'s amazing to see her so happy and passionate about it.',
    lastMessageTime: '1 day',
    unreadCount: 2,
  },
  {
    id: 'chat-10',
    name: 'Biron Alison',
    initials: 'BA',
    isOnline: false,
    lastMessage: 'Yeah, she mentioned it last week.',
    lastMessageTime: '1 day',
  },
  {
    id: 'chat-11',
    name: 'Baily Younie',
    initials: 'BY',
    isOnline: false,
    lastMessage: 'Thanks, I appreciate it!',
    lastMessageTime: 'Yesterday',
    unreadCount: 2,
  },
  {
    id: 'chat-12',
    name: 'Lawton Broadbury',
    initials: 'LB',
    isOnline: false,
    lastMessage: 'Drive safe!',
    lastMessageTime: '1 hours',
  },
  {
    id: 'chat-13',
    name: 'Ealasaid Bohlje',
    initials: 'EB',
    isOnline: false,
    lastMessage: 'I might be 10 minutes late. Sorry!',
    lastMessageTime: '10 days',
  },
]

// Mock messages for each chat
export const mockMessages: Record<string, ChatMessage[]> = {
  'chat-1': [
    {
      id: 'msg-1-1',
      senderId: 'user-1',
      content: 'Sorry :( send you as soon as possible.',
      timestamp: '05:20 PM',
      isRead: true,
      messageType: 'text',
    },
    {
      id: 'msg-1-2',
      senderId: CURRENT_USER_ID,
      content: 'I know how important this file is to you. You can trust me ;) I know how important this file is to you. You can trust me ;) know how important this file is to you. You can trust me ;)',
      timestamp: '05:22 PM',
      isRead: true,
      messageType: 'text',
    },
    {
      id: 'msg-1-3',
      senderId: CURRENT_USER_ID,
      content: 'I know how important this file is to you. You can trust me ;) me ;)',
      timestamp: '05:23 PM',
      isRead: true,
      messageType: 'text',
    },
    {
      id: 'msg-1-4',
      senderId: 'user-1',
      content: '',
      timestamp: '05:24 PM',
      isRead: true,
      messageType: 'image',
      attachments: [
        { url: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400', type: 'image' },
        { url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', type: 'image' },
      ],
    },
  ],
  'chat-2': [
    {
      id: 'msg-2-1',
      senderId: CURRENT_USER_ID,
      content: 'Hey! Are we still on for dinner tonight?',
      timestamp: '04:30 PM',
      isRead: true,
      messageType: 'text',
    },
    {
      id: 'msg-2-2',
      senderId: 'user-2',
      content: 'Yes! I\'m really looking forward to it. Where should we meet?',
      timestamp: '04:35 PM',
      isRead: true,
      messageType: 'text',
    },
    {
      id: 'msg-2-3',
      senderId: CURRENT_USER_ID,
      content: 'How about that new Italian place downtown? I heard great things about it.',
      timestamp: '04:40 PM',
      isRead: true,
      messageType: 'text',
    },
    {
      id: 'msg-2-4',
      senderId: 'user-2',
      content: 'Sounds perfect! I\'ve been wanting to try that place. See you there!',
      timestamp: '04:45 PM',
      isRead: false,
      messageType: 'text',
    },
  ],
  'chat-3': [
    {
      id: 'msg-3-1',
      senderId: 'user-3',
      content: 'How about 7 PM at the new Italian place downtown?',
      timestamp: '08:00 PM',
      isRead: true,
      messageType: 'text',
    },
  ],
  'chat-4': [
    {
      id: 'msg-4-1',
      senderId: 'user-4',
      content: 'Hey Bonnie, yes, definitely! What time should we meet?',
      timestamp: '10:00 AM',
      isRead: true,
      messageType: 'text',
    },
  ],
  'chat-5': [
    {
      id: 'msg-5-1',
      senderId: 'user-5',
      content: 'No worries at all! I\'ll grab a table and wait for you. Drive safe!',
      timestamp: '02:30 PM',
      isRead: true,
      messageType: 'text',
    },
  ],
  'chat-6': [
    {
      id: 'msg-6-1',
      senderId: 'user-6',
      content: 'She just told me today.',
      timestamp: '11:20 AM',
      isRead: true,
      messageType: 'text',
    },
  ],
  'chat-7': [
    {
      id: 'msg-7-1',
      senderId: 'user-7',
      content: 'See you in 5 minutes!',
      timestamp: '03:15 PM',
      isRead: true,
      messageType: 'text',
    },
  ],
  'chat-8': [
    {
      id: 'msg-8-1',
      senderId: 'user-8',
      content: 'If it takes long you can mail',
      timestamp: '09:45 AM',
      isRead: true,
      messageType: 'text',
    },
  ],
  'chat-9': [
    {
      id: 'msg-9-1',
      senderId: CURRENT_USER_ID,
      content: 'Did you see the latest update?',
      timestamp: '01:00 PM',
      isRead: true,
      messageType: 'text',
    },
    {
      id: 'msg-9-2',
      senderId: 'user-9',
      content: 'Absolutely! It\'s amazing to see her so happy and passionate about it.',
      timestamp: '01:05 PM',
      isRead: false,
      messageType: 'text',
    },
  ],
  'chat-10': [
    {
      id: 'msg-10-1',
      senderId: 'user-10',
      content: 'Yeah, she mentioned it last week.',
      timestamp: '12:30 PM',
      isRead: true,
      messageType: 'text',
    },
  ],
  'chat-11': [
    {
      id: 'msg-11-1',
      senderId: CURRENT_USER_ID,
      content: 'I\'ve sent the files over. Let me know if you need anything else.',
      timestamp: '10:15 AM',
      isRead: true,
      messageType: 'text',
    },
    {
      id: 'msg-11-2',
      senderId: 'user-11',
      content: 'Thanks, I appreciate it!',
      timestamp: '10:20 AM',
      isRead: false,
      messageType: 'text',
    },
  ],
  'chat-12': [
    {
      id: 'msg-12-1',
      senderId: 'user-12',
      content: 'Drive safe!',
      timestamp: '06:00 PM',
      isRead: true,
      messageType: 'text',
    },
  ],
  'chat-13': [
    {
      id: 'msg-13-1',
      senderId: 'user-13',
      content: 'I might be 10 minutes late. Sorry!',
      timestamp: '02:00 PM',
      isRead: true,
      messageType: 'text',
    },
  ],
}

