import {
  Briefcase,
  Users,
  Package,
  Headphones,
  BarChart3,
  PenTool,
  ClipboardList,
  DollarSign,
  Wrench,
  Megaphone,
  type LucideIcon,
} from 'lucide-react'
import { AIAgent } from '@/components/home/types'

export const aiAgents: AIAgent[] = [
  {
    id: 'sales-assistant',
    name: 'Sales Assistant',
    description: 'Helps with lead management and sales processes',
    category: 'Sales',
    icon: Briefcase,
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'hr-helper',
    name: 'HR Helper',
    description: 'Assists with employee management and HR tasks',
    category: 'HR',
    icon: Users,
    color: 'from-purple-500 to-pink-500',
  },
  {
    id: 'operations-manager',
    name: 'Operations Manager',
    description: 'Manages orders, shipments, and operations',
    category: 'Operations',
    icon: Package,
    color: 'from-orange-500 to-red-500',
  },
  {
    id: 'customer-support',
    name: 'Customer Support',
    description: 'Handles customer inquiries and support tickets',
    category: 'Support',
    icon: Headphones,
    color: 'from-green-500 to-emerald-500',
  },
  {
    id: 'data-analyst',
    name: 'Data Analyst',
    description: 'Provides insights and analytics',
    category: 'Analytics',
    icon: BarChart3,
    color: 'from-indigo-500 to-blue-500',
  },
  {
    id: 'content-writer',
    name: 'Content Writer',
    description: 'Helps with content creation and documentation',
    category: 'Content',
    icon: PenTool,
    color: 'from-yellow-500 to-amber-500',
  },
  {
    id: 'project-manager',
    name: 'Project Manager',
    description: 'Assists with project planning and tracking',
    category: 'Project',
    icon: ClipboardList,
    color: 'from-teal-500 to-cyan-500',
  },
  {
    id: 'finance-advisor',
    name: 'Finance Advisor',
    description: 'Helps with financial analysis and budgeting',
    category: 'Finance',
    icon: DollarSign,
    color: 'from-emerald-500 to-green-500',
  },
  {
    id: 'technical-support',
    name: 'Technical Support',
    description: 'Provides technical assistance and troubleshooting',
    category: 'Technical',
    icon: Wrench,
    color: 'from-slate-500 to-gray-500',
  },
  {
    id: 'marketing-specialist',
    name: 'Marketing Specialist',
    description: 'Assists with marketing campaigns and assets',
    category: 'Marketing',
    icon: Megaphone,
    color: 'from-pink-500 to-rose-500',
  },
]

