import {
  LayoutDashboard,
  CheckSquare,
  UserPlus,
  UserCog,
  Users,
  Briefcase,
  Building,
  ShoppingBag,
  Phone,
  Megaphone,
  BookOpen,
  FolderOpen,
  FileText,
  MessageSquare,
  Mail,
  Calendar,
  Ticket,
  Clock,
  CreditCard,
  Settings2,
  BriefcaseBusiness,
  Users2,
  Package,
  ShoppingCart,
  type LucideIcon,
} from 'lucide-react'
import { QuickLink } from '@/components/home/types'

export const quickLinks: QuickLink[] = [
  // Main
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Overview of key metrics and insights',
    url: '/dashboard',
    icon: LayoutDashboard,
    category: 'Main',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'tasks',
    title: 'Tasks',
    description: 'Manage and track your tasks',
    url: '/tasks',
    icon: CheckSquare,
    category: 'Main',
    color: 'from-green-500 to-emerald-500',
  },
  // People
  {
    id: 'users',
    title: 'Users',
    description: 'Manage user accounts and permissions',
    url: '/users',
    icon: UserPlus,
    category: 'People',
    color: 'from-purple-500 to-pink-500',
  },
  {
    id: 'employees',
    title: 'Employees',
    description: 'Employee directory and management',
    url: '/employees',
    icon: UserCog,
    category: 'People',
    color: 'from-indigo-500 to-purple-500',
  },
  // CRM
  {
    id: 'leads',
    title: 'Leads',
    description: 'Track and manage sales leads',
    url: '/crm/leads',
    icon: Users,
    category: 'CRM',
    color: 'from-orange-500 to-red-500',
  },
  {
    id: 'opportunities',
    title: 'Opportunities',
    description: 'Sales opportunities pipeline',
    url: '/crm/opportunities',
    icon: Briefcase,
    category: 'CRM',
    color: 'from-amber-500 to-orange-500',
    comingSoon: true,
  },
  {
    id: 'quotations',
    title: 'Quotations',
    description: 'Create and manage quotations',
    url: '/crm/quotations',
    icon: FileText,
    category: 'CRM',
    color: 'from-teal-500 to-cyan-500',
  },
  {
    id: 'contacts',
    title: 'Contacts',
    description: 'Manage customer contacts',
    url: '/crm/contacts',
    icon: Building,
    category: 'CRM',
    color: 'from-blue-500 to-indigo-500',
    comingSoon: true,
  },
  {
    id: 'companies',
    title: 'Companies',
    description: 'Company directory and profiles',
    url: '/crm/companies',
    icon: Building,
    category: 'CRM',
    color: 'from-slate-500 to-gray-500',
    comingSoon: true,
  },
  {
    id: 'products',
    title: 'Products',
    description: 'Product catalog management',
    url: '/crm/products',
    icon: ShoppingBag,
    category: 'CRM',
    color: 'from-violet-500 to-purple-500',
  },
  {
    id: 'calls',
    title: 'Calls',
    description: 'Track sales calls and interactions',
    url: '/crm/calls',
    icon: Phone,
    category: 'CRM',
    color: 'from-green-500 to-teal-500',
  },
  {
    id: 'marketing-assets',
    title: 'Marketing Assets',
    description: 'Manage marketing materials',
    url: '/crm/marketing-assets',
    icon: Megaphone,
    category: 'CRM',
    color: 'from-pink-500 to-rose-500',
  },
  // Knowledge
  {
    id: 'knowledge-articles',
    title: 'Knowledge Base',
    description: 'Browse knowledge articles',
    url: '/knowledge/articles',
    icon: BookOpen,
    category: 'Knowledge',
    color: 'from-yellow-500 to-amber-500',
  },
  {
    id: 'sops',
    title: 'SOPs',
    description: 'Standard operating procedures',
    url: '/knowledge/sops',
    icon: FolderOpen,
    category: 'Knowledge',
    color: 'from-cyan-500 to-blue-500',
    comingSoon: true,
  },
  {
    id: 'files',
    title: 'Files',
    description: 'Document and file management',
    url: '/knowledge/files',
    icon: FileText,
    category: 'Knowledge',
    color: 'from-gray-500 to-slate-500',
    comingSoon: true,
  },
  {
    id: 'docs',
    title: 'Documentation',
    description: 'Technical documentation',
    url: '/knowledge/docs',
    icon: FileText,
    category: 'Knowledge',
    color: 'from-slate-500 to-gray-500',
    comingSoon: true,
  },
  // Communication
  {
    id: 'messages',
    title: 'Messages',
    description: 'Internal messaging system',
    url: '/messages',
    icon: MessageSquare,
    category: 'Communication',
    color: 'from-blue-500 to-indigo-500',
  },
  {
    id: 'mail',
    title: 'Mail',
    description: 'Email client and management',
    url: '/mail',
    icon: Mail,
    category: 'Communication',
    color: 'from-red-500 to-pink-500',
  },
  {
    id: 'calendar',
    title: 'Calendar',
    description: 'Schedule and manage events',
    url: '/calendar',
    icon: Calendar,
    category: 'Communication',
    color: 'from-green-500 to-emerald-500',
    comingSoon: true,
  },
  // Operations
  {
    id: 'tickets',
    title: 'Tickets',
    description: 'Support ticket management',
    url: '/tickets',
    icon: Ticket,
    category: 'Operations',
    color: 'from-orange-500 to-amber-500',
    comingSoon: true,
  },
  {
    id: 'documents',
    title: 'Documents',
    description: 'Document management system',
    url: '/documents',
    icon: FileText,
    category: 'Operations',
    color: 'from-blue-500 to-cyan-500',
    comingSoon: true,
  },
  {
    id: 'attendance',
    title: 'HR Attendance',
    description: 'Employee attendance tracking',
    url: '/hr/attendance',
    icon: Clock,
    category: 'Operations',
    color: 'from-purple-500 to-violet-500',
    comingSoon: true,
  },
  {
    id: 'subscriptions',
    title: 'Subscriptions',
    description: 'Manage subscriptions and renewals',
    url: '/subscriptions',
    icon: CreditCard,
    category: 'Operations',
    color: 'from-indigo-500 to-blue-500',
    comingSoon: true,
  },
  // Settings
  {
    id: 'settings-general',
    title: 'General Settings',
    description: 'General application settings',
    url: '/settings/general',
    icon: Settings2,
    category: 'Settings',
    color: 'from-gray-500 to-slate-500',
    comingSoon: true,
  },
  {
    id: 'permissions',
    title: 'Permissions',
    description: 'Manage user permissions',
    url: '/settings/permissions',
    icon: BriefcaseBusiness,
    category: 'Settings',
    color: 'from-red-500 to-orange-500',
    comingSoon: true,
  },
  {
    id: 'rbac',
    title: 'RBAC',
    description: 'Role-based access control',
    url: '/settings/rbac',
    icon: Users2,
    category: 'Settings',
    color: 'from-blue-500 to-indigo-500',
    comingSoon: true,
  },
  {
    id: 'team',
    title: 'Team Settings',
    description: 'Team management and configuration',
    url: '/settings/team',
    icon: Users2,
    category: 'Settings',
    color: 'from-green-500 to-teal-500',
    comingSoon: true,
  },
  // Verticals
  {
    id: 'ats',
    title: 'ATS',
    description: 'Applicant tracking system',
    url: '/ats',
    icon: FileText,
    category: 'Verticals',
    color: 'from-purple-500 to-pink-500',
    comingSoon: true,
  },
  {
    id: 'ops',
    title: 'Operations',
    description: 'Operations management',
    url: '/ops',
    icon: ShoppingCart,
    category: 'Verticals',
    color: 'from-blue-500 to-cyan-500',
    comingSoon: true,
  },
  {
    id: 'import-ops',
    title: 'Import Ops',
    description: 'Import operations management',
    url: '/import-ops',
    icon: Package,
    category: 'Verticals',
    color: 'from-orange-500 to-amber-500',
    comingSoon: true,
  },
]

