import * as LucideIcons from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { LayoutDashboard } from 'lucide-react' // Default fallback icon

/**
 * Maps icon name strings to Lucide React icon components
 * Handles missing icons gracefully with a fallback
 */
export function getIcon(iconName: string | undefined): LucideIcon {
  if (!iconName) {
    return LayoutDashboard
  }

  // If it's already a component, return it
  if (typeof iconName !== 'string') {
    return iconName as LucideIcon
  }

  // Convert kebab-case or PascalCase to PascalCase
  const pascalCase = iconName
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')

  // Try to get the icon from lucide-react
  const Icon = (LucideIcons as any)[pascalCase] || (LucideIcons as any)[iconName]

  if (Icon && typeof Icon === 'function') {
    return Icon as LucideIcon
  }

  // Fallback to default icon if not found
  console.warn(`Icon "${iconName}" not found, using default LayoutDashboard icon`)
  return LayoutDashboard
}

/**
 * Icon name registry for common icons used in navigation
 * This helps with autocomplete and type safety
 */
export const NAV_ICONS = {
  LayoutDashboard: 'LayoutDashboard',
  Home: 'Home',
  Activity: 'Activity',
  Users: 'Users',
  CreditCard: 'CreditCard',
  KeyRound: 'KeyRound',
  Search: 'Search',
  Plug: 'Plug',
  ShieldCheck: 'ShieldCheck',
  Server: 'Server',
  Webhook: 'Webhook',
  ListTree: 'ListTree',
  Settings: 'Settings',
  Lock: 'Lock',
  Receipt: 'Receipt',
  Trophy: 'Trophy',
  Bookmark: 'Bookmark',
  Store: 'Store',
  Download: 'Download',
  Sparkles: 'Sparkles',
  TrendingUp: 'TrendingUp',
  Calculator: 'Calculator',
  Handshake: 'Handshake',
  Scale: 'Scale',
  FileText: 'FileText',
  ShoppingCart: 'ShoppingCart',
  Package: 'Package',
  Globe: 'Globe',
  Building: 'Building',
  Briefcase: 'Briefcase',
  Phone: 'Phone',
  Mail: 'Mail',
  Calendar: 'Calendar',
  Clock: 'Clock',
  Tag: 'Tag',
  CheckSquare: 'CheckSquare',
  FolderOpen: 'FolderOpen',
  MessageSquare: 'MessageSquare',
  UserCog: 'UserCog',
  TrendingDown: 'TrendingDown',
  BarChart: 'BarChart',
  PieChart: 'PieChart',
  LineChart: 'LineChart',
  Database: 'Database',
  Network: 'Network',
  Zap: 'Zap',
  Bell: 'Bell',
  HelpCircle: 'HelpCircle',
  BookOpen: 'BookOpen',
  FileCheck: 'FileCheck',
  Shield: 'Shield',
  AlertCircle: 'AlertCircle',
  Info: 'Info',
  ChevronRight: 'ChevronRight',
  ChevronLeft: 'ChevronLeft',
  ArrowRight: 'ArrowRight',
  ArrowLeft: 'ArrowLeft',
  Plus: 'Plus',
  Minus: 'Minus',
  X: 'X',
  Check: 'Check',
  Edit: 'Edit',
  Trash: 'Trash',
  Eye: 'Eye',
  EyeOff: 'EyeOff',
  MoreVertical: 'MoreVertical',
  MoreHorizontal: 'MoreHorizontal',
  Filter: 'Filter',
  SortAsc: 'SortAsc',
  SortDesc: 'SortDesc',
  RefreshCw: 'RefreshCw',
  Download: 'Download',
  Upload: 'Upload',
  Share: 'Share',
  Copy: 'Copy',
  ExternalLink: 'ExternalLink',
  Link: 'Link',
  Unlink: 'Unlink',
  Image: 'Image',
  Video: 'Video',
  Music: 'Music',
  File: 'File',
  Folder: 'Folder',
  FolderPlus: 'FolderPlus',
  FilePlus: 'FilePlus',
  Save: 'Save',
  SaveAll: 'SaveAll',
  Printer: 'Printer',
  Archive: 'Archive',
  ArchiveRestore: 'ArchiveRestore',
  Trash2: 'Trash2',
  Undo: 'Undo',
  Redo: 'Redo',
  History: 'History',
  Clock: 'Clock',
  Calendar: 'Calendar',
  CalendarDays: 'CalendarDays',
  CalendarCheck: 'CalendarCheck',
  CalendarX: 'CalendarX',
  Timer: 'Timer',
  Stopwatch: 'Stopwatch',
  Hourglass: 'Hourglass',
  AlarmClock: 'AlarmClock',
  Bell: 'Bell',
  BellOff: 'BellOff',
  BellRing: 'BellRing',
  Volume2: 'Volume2',
  VolumeX: 'VolumeX',
  Volume1: 'Volume1',
  Mic: 'Mic',
  MicOff: 'MicOff',
  Video: 'Video',
  VideoOff: 'VideoOff',
  Camera: 'Camera',
  CameraOff: 'CameraOff',
  Monitor: 'Monitor',
  MonitorOff: 'MonitorOff',
  Smartphone: 'Smartphone',
  Tablet: 'Tablet',
  Laptop: 'Laptop',
  Desktop: 'Desktop',
  Tv: 'Tv',
  Radio: 'Radio',
  Headphones: 'Headphones',
  Speaker: 'Speaker',
  Airplay: 'Airplay',
  Cast: 'Cast',
  Bluetooth: 'Bluetooth',
  Wifi: 'Wifi',
  WifiOff: 'WifiOff',
  Signal: 'Signal',
  SignalHigh: 'SignalHigh',
  SignalLow: 'SignalLow',
  SignalZero: 'SignalZero',
  Zap: 'Zap',
  ZapOff: 'ZapOff',
  Power: 'Power',
  PowerOff: 'PowerOff',
  Battery: 'Battery',
  BatteryCharging: 'BatteryCharging',
  BatteryFull: 'BatteryFull',
  BatteryLow: 'BatteryLow',
  BatteryMedium: 'BatteryMedium',
  Plug: 'Plug',
  PlugZap: 'PlugZap',
  PlugZap2: 'PlugZap2',
  Cable: 'Cable',
  Usb: 'Usb',
  HardDrive: 'HardDrive',
  HardDriveIcon: 'HardDriveIcon',
  Database: 'Database',
  DatabaseBackup: 'DatabaseBackup',
  DatabaseRestore: 'DatabaseRestore',
  Server: 'Server',
  ServerCrash: 'ServerCrash',
  ServerOff: 'ServerOff',
  Cloud: 'Cloud',
  CloudOff: 'CloudOff',
  CloudUpload: 'CloudUpload',
  CloudDownload: 'CloudDownload',
  CloudRain: 'CloudRain',
  CloudSnow: 'CloudSnow',
  CloudLightning: 'CloudLightning',
  CloudDrizzle: 'CloudDrizzle',
  CloudFog: 'CloudFog',
  CloudHail: 'CloudHail',
  CloudSleet: 'CloudSleet',
  CloudSun: 'CloudSun',
  CloudMoon: 'CloudMoon',
  Cloudy: 'Cloudy',
  Sun: 'Sun',
  Moon: 'Moon',
  Star: 'Star',
  Stars: 'Stars',
  Sunrise: 'Sunrise',
  Sunset: 'Sunset',
  Droplet: 'Droplet',
  Droplets: 'Droplets',
  Umbrella: 'Umbrella',
  Wind: 'Wind',
  Tornado: 'Tornado',
  Hurricane: 'Hurricane',
  Snowflake: 'Snowflake',
  Thermometer: 'Thermometer',
  ThermometerSun: 'ThermometerSun',
  ThermometerSnowflake: 'ThermometerSnowflake',
  Heart: 'Heart',
  Truck: 'Truck',
  Trophy: 'Trophy',
  ShieldCheck: 'ShieldCheck',
  Webhook: 'Webhook',
  HelpCircle: 'HelpCircle',
  Sparkles: 'Sparkles',
  Share: 'Share',
  Upload: 'Upload',
  Archive: 'Archive',
  History: 'History',
} as const

export type NavIconName = keyof typeof NAV_ICONS

